### ISSUE TITLE
As a pop culture fan, I want to get learn Game of Thrones trivia, so that I can engage in after-work small-talk.

### ISSUE THREAD

**Issue by Quoc-V** [code4policy/GoT-Universe#1]
Connect information database

 Visualize general information

**Comment by dmil** [comment]
*INVEST*
- [x] Independent
- [x] Negotiable
- [x] Valuable
- [x] Estimable
- [x] Small
- [x] Testable

## TASKS
- Make a blank website
- Collect facts
- Create small database of facts
- Put five facts about GoT on that website

## DEFINITION OF DONE
- Show it to a game of thrones fan, and have them say they learned a few facts.

**Comment by llewrubnala** [comment]
Splitting story into substories, closing this issue.
