### ISSUE TITLE
As a new GoT Viewer, I want a site that provides an overview and context to the world so that I can better understand the plot and characters

### ISSUE THREAD

**Issue by goldenbearpolicyshop** [code4policy/GoT-Universe#2]

**Comment by goldenbearpolicyshop** [comment]
*INVEST*
- [x] Independent
- [x] Negotiable
- [x] Valuable
- [x] Estimable
- [x] Small
- [x] Testable

## TASKS
- Make a blank website
- Render a map image of Westeros on the website
- Update information to reflect the current state of information
- Add images, colorschemes, and fonts that fit the fantasy context of GoT


## DEFINITION OF DONE
- Game of Thrones new viewers will be able to tell you where the major houses are located and basic information about them

**Comment by llewrubnala** [comment]
Closing issue; breaking into separate stories.
