### ISSUE TITLE
As a pop culture fan, I want a website to learn GoT trivia, so that I can engage in after-work small-talk.

### ISSUE THREAD

**Issue by llewrubnala** [code4policy/GoT-Universe#4]

**Comment by llewrubnala** [comment]
## INVEST

- [x] Independent
- [x] Negotiable
- [x] Valuable
- [x] Estimable
- [x] Small
- [x] Testable

## TASKS

- Make a blank website, if required
- Collect or create database of GoT trivia with minimum 10 facts
- Update website to include facts
- Update facts to scroll or update

## DEFINITION OF DONE

- Show website to pop culture fan and see if they've learned 5 facts.

**Comment by goldenbearpolicyshop** [comment]
https://www.freecodecamp.org/news/creating-a-bare-bones-quote-generator-with-javascript-and-html-for-absolute-beginners-5264e1725f08/

**Comment by goldenbearpolicyshop** [comment]
https://www.w3resource.com/javascript-exercises/javascript-array-exercise-35.php
